spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catastrofescl_resources_test
    username: catastrofescl
    password: catastrofescl
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

catastrofescl:
  auth:
    dev-mode: true
  firebase:
    enabled: false
  rabbitmq:
    exchange-topic: catastrofescl.events
    exchange-dlx: catastrofescl.dlx
    cola-emergencia-creada: ms-resources.emergencia-creada.test
    cola-emergencia-creada-dlq: ms-resources.emergencia-creada.dlq.test
